version: "3.9"

services:
  dist-22-23s-app:
    container_name: dist-22-23s-app
    build:
      context: ./DistributedSystems
      dockerfile: Dockerfile
    ports:
      # external:internal
      - "8000:80"
    depends_on:
      - dist-22-23s-db
    environment:
      - ConnectionStrings:DefaultConnection=Host=dist-22-23s-db;Database=plant-app;Username=postgres;Password=postgres
  
  dist-22-23s-db:
    container_name: dist-22-23s-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"
    volumes:
      - dist-22-23s-db-postgres-volume:/var/lib/postgresql/data

volumes:
  dist-22-23s-db-postgres-volume:
